/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yt_androidtv_testjni_StringKit */

#ifndef _Included_com_yt_androidtv_testjni_StringKit
#define _Included_com_yt_androidtv_testjni_StringKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yt_androidtv_testjni_StringKit
 * Method:    setNull
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yt_androidtv_testjni_StringKit_setNull
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
